language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t mcrawford/docker-react .

script:
  - docker run -e CI=true mcrawford/docker-react npm run test
 