language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t mcrawford/docker-react .

script:
  - docker run -e CI=true mcrawford/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: docker
  env: Docker-env
  bucket_name: elasticbeanstalk-us-west-2-692874983914
  bucket_path: docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
